"""
Shared fixtures for the SDK test suite.

Two scopes intentionally:
  - `client` / `mock_backend`: hermetic, used by tests/test_contract_*.
  - `tiny_pdf` / `tiny_png`: small generated bytes, used as request bodies.

The L2 customer simulator lives under tests/customer_sim/ and is *not* invoked
by pytest — it's run via `python -m tests.customer_sim`. Pytest only exercises
the L1 mocked contract suite.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from hyperapi import AsyncHyperAPIClient, HyperAPIClient


TEST_BASE_URL = "http://test.local"
TEST_API_KEY = "hk_test_unit"


# ── Environment hygiene ─────────────────────────────────────────────────────


@pytest.fixture(autouse=True)
def _clean_env(monkeypatch):
    """Strip proxy and SDK env vars so tests are reproducible regardless of host shell.

    Without this, a developer with HTTP(S)_PROXY or HYPERAPI_KEY set in their
    environment would either see httpx try to reach a proxy or pick up the
    wrong API key. CI is also clean, but devs hit this constantly.
    """
    for var in (
        "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "NO_PROXY",
        "http_proxy", "https_proxy", "all_proxy", "no_proxy",
        "HYPERAPI_KEY", "HYPERAPI_URL", "HYPERAPI_VERIFY",
    ):
        monkeypatch.delenv(var, raising=False)


# ── Hermetic client/backend pair ────────────────────────────────────────────


@pytest.fixture
def client():
    """Default client with poll_interval=0 + small poll_timeout so tests don't actually sleep."""
    c = HyperAPIClient(
        api_key=TEST_API_KEY,
        base_url=TEST_BASE_URL,
        poll_interval=0.0,
        poll_timeout=5.0,
        poll_max_transient_retries=2,
    )
    yield c
    c.close()


@pytest.fixture
def slow_poll_client():
    """Client with a short positive poll_interval, for tests that need to assert
    the SDK actually sleeps between polls."""
    c = HyperAPIClient(
        api_key=TEST_API_KEY,
        base_url=TEST_BASE_URL,
        poll_interval=0.05,
        poll_timeout=5.0,
        poll_max_transient_retries=2,
    )
    yield c
    c.close()


# ── Async fixtures (mirror the sync ones; asyncio_mode = "auto" picks these up) ─


@pytest.fixture
async def async_client():
    """Async client with poll_interval=0 + small poll_timeout so tests don't actually sleep."""
    c = AsyncHyperAPIClient(
        api_key=TEST_API_KEY,
        base_url=TEST_BASE_URL,
        poll_interval=0.0,
        poll_timeout=5.0,
        poll_max_transient_retries=2,
    )
    yield c
    await c.aclose()


@pytest.fixture
async def slow_poll_async_client():
    """Async client with a short positive poll_interval, for tests that need to
    assert the SDK actually yields between polls."""
    c = AsyncHyperAPIClient(
        api_key=TEST_API_KEY,
        base_url=TEST_BASE_URL,
        poll_interval=0.05,
        poll_timeout=5.0,
        poll_max_transient_retries=2,
    )
    yield c
    await c.aclose()


@pytest.fixture
def mock_backend():
    """Activated respx router scoped to TEST_BASE_URL."""
    import respx

    with respx.mock(base_url=TEST_BASE_URL, assert_all_called=False) as router:
        yield router


# ── Minimal real bytes for upload paths ─────────────────────────────────────


_MINIMAL_PDF = (
    b"%PDF-1.4\n"
    b"1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj\n"
    b"2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>> endobj\n"
    b"3 0 obj <</Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]>> endobj\n"
    b"xref\n0 4\n0000000000 65535 f\n"
    b"trailer <</Size 4 /Root 1 0 R>>\nstartxref\n%%EOF\n"
)


@pytest.fixture
def tiny_pdf(tmp_path: Path) -> Path:
    p = tmp_path / "doc.pdf"
    p.write_bytes(_MINIMAL_PDF)
    return p


@pytest.fixture
def tiny_png(tmp_path: Path) -> Path:
    """Smallest valid 1x1 PNG, no Pillow needed."""
    p = tmp_path / "img.png"
    p.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        b"\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00"
        b"\x1f\x15\xc4\x89"
        b"\x00\x00\x00\rIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4"
        b"\x00\x00\x00\x00IEND\xaeB`\x82",
    )
    return p


@pytest.fixture
def tiny_jpg(tmp_path: Path) -> Path:
    """Tiny placeholder bytes — respx doesn't validate the body, the SDK only
    needs *some* file at the path to feed httpx."""
    p = tmp_path / "img.jpg"
    p.write_bytes(b"\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xd9")
    return p
